CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ingest_id UUID NOT NULL DEFAULT uuid_generate_v4(),
    event_type TEXT NOT NULL,
    event_time TIMESTAMPTZ NOT NULL,
    domain TEXT,
    entity_id TEXT,
    service TEXT,
    context_id TEXT,
    parent_context_id TEXT,
    user_id TEXT,
    source TEXT NOT NULL DEFAULT 'home_assistant',
    dedupe_key TEXT,
    collector_instance TEXT NOT NULL DEFAULT 'unknown',
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
) PARTITION BY RANGE (event_time);

CREATE OR REPLACE FUNCTION ensure_events_partition_for_day(target_day DATE)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    partition_name TEXT := format('events_p%s', to_char(target_day, 'YYYYMMDD'));
    partition_start TIMESTAMPTZ := (target_day::timestamp AT TIME ZONE 'UTC');
    partition_end TIMESTAMPTZ := ((target_day + 1)::timestamp AT TIME ZONE 'UTC');
BEGIN
    EXECUTE format(
        'CREATE TABLE IF NOT EXISTS %I PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
        partition_name,
        partition_start,
        partition_end
    );
END;
$$;

CREATE OR REPLACE FUNCTION ensure_events_partitions(from_day DATE, to_day DATE)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    current_day DATE := from_day;
    created_count INTEGER := 0;
    partition_name TEXT;
BEGIN
    IF to_day < from_day THEN
        RETURN 0;
    END IF;

    WHILE current_day <= to_day LOOP
        partition_name := format('events_p%s', to_char(current_day, 'YYYYMMDD'));
        IF to_regclass(partition_name) IS NULL THEN
            created_count := created_count + 1;
        END IF;
        PERFORM ensure_events_partition_for_day(current_day);
        current_day := current_day + 1;
    END LOOP;

    RETURN created_count;
END;
$$;

CREATE OR REPLACE FUNCTION drop_events_partitions_older_than(cutoff_day DATE)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
    dropped_count INTEGER := 0;
    partition_row RECORD;
    partition_day DATE;
BEGIN
    FOR partition_row IN
        SELECT child.relname AS partition_name
        FROM pg_inherits inh
        JOIN pg_class parent ON parent.oid = inh.inhparent
        JOIN pg_class child ON child.oid = inh.inhrelid
        WHERE parent.relname = 'events'
          AND child.relname ~ '^events_p[0-9]{8}$'
    LOOP
        partition_day := to_date(substring(partition_row.partition_name FROM 'events_p([0-9]{8})'), 'YYYYMMDD');
        IF partition_day < cutoff_day THEN
            EXECUTE format('DROP TABLE IF EXISTS %I', partition_row.partition_name);
            dropped_count := dropped_count + 1;
        END IF;
    END LOOP;

    RETURN dropped_count;
END;
$$;

-- Create a baseline partition window on initial DB bootstrap.
SELECT ensure_events_partitions(CURRENT_DATE - 2, CURRENT_DATE + 14);

CREATE INDEX IF NOT EXISTS idx_events_id ON events (id);
CREATE INDEX IF NOT EXISTS idx_events_event_time ON events (event_time DESC);
CREATE INDEX IF NOT EXISTS idx_events_event_type ON events (event_type);
CREATE INDEX IF NOT EXISTS idx_events_domain ON events (domain);
CREATE INDEX IF NOT EXISTS idx_events_entity_id ON events (entity_id);
CREATE INDEX IF NOT EXISTS idx_events_context_id ON events (context_id);
CREATE INDEX IF NOT EXISTS idx_events_data_gin ON events USING GIN (data);
CREATE UNIQUE INDEX IF NOT EXISTS idx_events_event_time_dedupe_key_unique
    ON events (event_time, dedupe_key);
CREATE INDEX IF NOT EXISTS idx_events_context_time
    ON events (context_id, event_time DESC);
CREATE INDEX IF NOT EXISTS idx_events_parent_context_id
    ON events (parent_context_id);
CREATE INDEX IF NOT EXISTS idx_events_entity_time
    ON events (entity_id, event_time DESC);
CREATE INDEX IF NOT EXISTS idx_events_service_time
    ON events (service, event_time DESC)
    WHERE service IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_events_collector_received
    ON events (collector_instance, received_at DESC);

CREATE TABLE IF NOT EXISTS entity_snapshots (
    id BIGSERIAL PRIMARY KEY,
    entity_id TEXT NOT NULL,
    state TEXT,
    domain TEXT,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    context_id TEXT,
    captured_at TIMESTAMPTZ NOT NULL,
    source_event_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_entity_snapshots_entity_time
    ON entity_snapshots (entity_id, captured_at DESC);

CREATE TABLE IF NOT EXISTS automation_snapshots (
    id BIGSERIAL PRIMARY KEY,
    automation_id TEXT NOT NULL,
    alias TEXT,
    is_enabled BOOLEAN,
    trigger_config JSONB NOT NULL DEFAULT '[]'::jsonb,
    action_config JSONB NOT NULL DEFAULT '[]'::jsonb,
    conditions_config JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    captured_at TIMESTAMPTZ NOT NULL,
    source_event_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_automation_snapshots_auto_time
    ON automation_snapshots (automation_id, captured_at DESC);

CREATE TABLE IF NOT EXISTS trace_contexts (
    id BIGSERIAL PRIMARY KEY,
    context_id TEXT NOT NULL UNIQUE,
    root_context_id TEXT,
    related_context_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS agent_runs (
    id BIGSERIAL PRIMARY KEY,
    run_uuid UUID NOT NULL DEFAULT uuid_generate_v4(),
    run_type TEXT NOT NULL,
    status TEXT NOT NULL,
    window_start TIMESTAMPTZ,
    window_end TIMESTAMPTZ,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_runs_started_at ON agent_runs (started_at DESC);

CREATE TABLE IF NOT EXISTS insights (
    id BIGSERIAL PRIMARY KEY,
    agent_run_id BIGINT NOT NULL REFERENCES agent_runs(id) ON DELETE CASCADE,
    rank INT NOT NULL,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    root_cause TEXT,
    confidence NUMERIC(5,4),
    severity NUMERIC(5,4),
    recommendation JSONB,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_insights_agent_run_id ON insights (agent_run_id);

CREATE TABLE IF NOT EXISTS evidence (
    id BIGSERIAL PRIMARY KEY,
    evidence_uuid UUID NOT NULL DEFAULT uuid_generate_v4(),
    insight_id BIGINT REFERENCES insights(id) ON DELETE CASCADE,
    evidence_type TEXT NOT NULL,
    event_id BIGINT,
    entity_id TEXT,
    context_id TEXT,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_evidence_insight_id ON evidence (insight_id);
CREATE INDEX IF NOT EXISTS idx_evidence_event_id ON evidence (event_id);

CREATE TABLE IF NOT EXISTS analysis_results (
    id BIGSERIAL PRIMARY KEY,
    agent_run_id BIGINT REFERENCES agent_runs(id) ON DELETE CASCADE,
    report_markdown TEXT NOT NULL,
    report_json JSONB NOT NULL,
    published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS recommendations (
    id BIGSERIAL PRIMARY KEY,
    agent_run_id BIGINT REFERENCES agent_runs(id) ON DELETE CASCADE,
    insight_id BIGINT REFERENCES insights(id) ON DELETE SET NULL,
    recommendation_type TEXT NOT NULL,
    target_automation_id TEXT,
    change_payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'proposed',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
